/*
 * Tuple generated by datas from database
 * for table `ingredient`
 * - id
 * - nom
 * - description
 * - prix
 * - calories
 * - qte stock
 * - qte min
 * - image
 * - quantite
*/
pub type IngrFromDb = (Option<u32>, Option<String>, Option<String>, Option<f32>,
                   Option<u16>, Option<u8>, Option<u8>, Option<String>, Option<u8>);

/*
 * Tuple generated by datas from database
 * for table `burger`
 * - id
 * - nom
 * - prix
 * - description
 * - recette
 * - image
 * - quantite
*/
pub type BurFromDb = (Option<u32>, Option<String>, Option<f32>, Option<String>,
                   Option<String>, Option<String>, Option<u8>);

/*
 * Tuple generated by datas from database
 * for table `boisson`
 * - id
 * - nom
 * - prix
 * - description
 * - calories
 * - qte stock
 * - qte min
 * - image
 * - quantite
*/
pub type DrkFromDb = (Option<u32>, Option<String>, Option<f32>, Option<String>,
                   Option<u16>, Option<u8>, Option<u8>, Option<String>, Option<u8>);

/*
 * Tuple generated by datas from database
 * for table `commande`
 * - id
 * - n_table
 * - heure
 * - n_serveur
 * - paye
*/
pub type CmdFromDb = (Option<u32>, Option<u8>, Option<String>, Option<u8>, Option<u8>);
